service: study-monorepo-serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

functions:
  function1:
    handler: dist/function1/src/main.handler
    events:
      - http:
          method: GET
          path: /function1

  function2:
    handler: dist/function2/src/main.handler
    events:
      - http:
          method: GET
          path: /function2

  function3:
    handler: dist/function3/src/main.handler
    events:
      - http:
          method: GET
          path: /function3

custom:
  serverless-offline:
    httpPort: 3000
